POST http://app:8080/api/plants
Content-Type: application/json

{
    "name": "Hello",
    "specie": "Plante verte",
    "buyingDate": "2025-06-28",
    "status": "ALIVE",
    "diseases":null,
    "actions":null
}