POST http://app:8080/api/plants
Content-Type: application/json

{
    "name": "putain",
    "specie": "Plante verte",
    "buying_date": null,
    "status": "ALIVE",
    "diseases":null,
    "actions":null
}