PUT http://app:8080/api/plants/14
Content-Type: application/json

{
    "name": "coc",
    "specie": "Plante verte",
    "buying_date": "2025-06-28",
    "status": "DEAD",
    "diseases":null,
    "actions": null
}